### ISSUE TITLE
Enhancement for downloading large files

### ISSUE THREAD

**Issue by noeldap93** [jdarling/nodemcu_editor#7]
If you change plugins/serial/index.js line 113 from:
  `command: 'file.open("'+fileName+'", "r"); print("'+fileStart+'" .. file.read() .. "'+fileEnd+'"); file.close()'`
to:
`command: 'file.open("'+fileName+'", "r"); print("'+fileStart+'"); repeat  _str_line=file.readline(); if _str_line then uart.write(0,_str_line); else break; end; until false; print("'+fileEnd+'"); file.close()'
`
You can read larger files because file.read() has a buffer limit. Actually the editor can only read 1024 characters and crops files when reading it from the nodemcu.

**Comment by jdarling** [comment]
Thanks, pushed a new version with this change.
